21/05/05 04:00:25 1086.139807620884288 DEBUG utils.debug_sql (0.002) SELECT @@SQL_AUTO_IS_NULL; args=None
21/05/05 04:00:25 1086.139807620884288 DEBUG utils.debug_sql (0.000) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/05/05 04:00:25 1086.139807620884288 DEBUG utils.debug_sql (0.006) SHOW FULL TABLES; args=None
21/05/05 04:00:25 1086.139807620884288 DEBUG utils.debug_sql (0.007) SELECT `django_migrations`.`id`, `django_migrations`.`app`, `django_migrations`.`name`, `django_migrations`.`applied` FROM `django_migrations`; args=()
21/05/05 04:00:27 1527.139661663221568 DEBUG utils.debug_sql (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
21/05/05 04:00:27 1527.139661663221568 DEBUG utils.debug_sql (0.004) SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED; args=None
21/05/05 04:00:27 1527.139661663221568 DEBUG utils.debug_sql (0.000) SHOW FULL TABLES; args=None
21/05/05 04:00:27 1527.139661663221568 DEBUG utils.debug_sql (0.001) SELECT `django_migrations`.`id`, `django_migrations`.`app`, `django_migrations`.`name`, `django_migrations`.`applied` FROM `django_migrations`; args=()
Performing system checks...

System check identified no issues (0 silenced).

Django version 3.1.3, using settings 'meeting.settings'
Development server is running at https://0.0.0.0:8000/
Using the Werkzeug debugger (http://werkzeug.pocoo.org/)
Quit the server with CONTROL-C.
